### ISSUE TITLE
【报错】ImportError: No module named requests

### ISSUE THREAD

**Issue by StringKe** [LF112/BTCO#1]
CentOS Linux 7.6.1810 (Core)
6.9.15

```json
{
    "status":false,
    "msg":"抱歉，出错了：<br> Traceback (most recent call last):<br> File "class/panelPlugin.py", line 1542, in a<br> plugin_main = __import__(get.name+'_main');<br> File "/usr/lib64/python2.7/site-packages/gevent/builtins.py", line 96, in __import__<br> result = _import(*args, **kwargs)<br> File "plugin/btco/btco_main.py", line 23, in <module><br> import public, json, requests, math, panelAuth<br> File "/usr/lib64/python2.7/site-packages/gevent/builtins.py", line 96, in __import__<br> result = _import(*args, **kwargs)<br>ImportError: No module named requests<br> "
}
```

抱歉，出错了：<br> Traceback (most recent call last):<br> File "class/panelPlugin.py", line 1542, in a<br> plugin_main = __import__(get.name+'_main');<br> File "/usr/lib64/python2.7/site-packages/gevent/builtins.py", line 96, in __import__<br> result = _import(*args, **kwargs)<br> File "plugin/btco/btco_main.py", line 23, in <module><br> import public, json, requests, math, panelAuth<br> File "/usr/lib64/python2.7/site-packages/gevent/builtins.py", line 96, in __import__<br> result = _import(*args, **kwargs)<br>ImportError: No module named requests<br>

**Comment by LF112** [comment]
该报错是Python requests库不存在。
请在终端尝试安装此库
`pip install requests`
