### ISSUE TITLE
可以在github pages上用这个吗233

### ISSUE THREAD

**Issue by CuteSheep233** [LF112/BTCO#2]
rt,就是好奇能不能用，我感觉我在想屁吃awa

**Comment by LF112** [comment]
你在想Peach

**Comment by Jack2007Q** [comment]
无聊刷屏
HEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by LF112** [comment]
> 无聊刷屏
> HEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

缓缓地打出个¿
