### ISSUE TITLE
问一下

### ISSUE THREAD

**Issue by soxft** [LF112/BTCO#3]
为什么这个插件不做了啊，我感觉挺不错的啊

**Comment by LF112** [comment]
因为学习原因时间不够，再加上页面表现及JavaScript能力低下就暂时停止更新了。其次，考虑到还有其他优秀的插件会上架，我不能一直站着这个位置不动，所以就下架让给后面的插件了。

顺带一提，最近有考虑重构BTCO，还请多多关注哦！谢谢！
